### ISSUE TITLE
Noda Time fails in Blazor

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#1120]
Following https://blazor.net/docs/tutorials/build-your-first-blazor-app.html but then installing Noda Time 2.2.6 into the project, initially there's a build time failure [as per this issue](https://github.com/aspnet/Blazor/issues/356). Once you disable build-time linking (via `<BlazorLinkOnBuild>false</BlazorLinkOnBuild>`) we can at least run the app. Just displaying `@NodaTime.SystemClock.Instance.GetCurrentInstant()` throws an exception though:

```text
MonoPlatform.ts:70 Uncaught Error: System.TypeInitializationException: The type initializer for 'NodaTime.DateTimeZone' threw an exception. ---> System.ArgumentException: The start Instant must be less than the end Instant
Parameter name: start
  at NodaTime.Utility.Preconditions.CheckArgument (System.Boolean expression, System.String parameter, System.String message) <0x23f0988 + 0x00020> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at NodaTime.TimeZones.ZoneInterval..ctor (System.String name, NodaTime.Instant start, NodaTime.Instant end, NodaTime.Offset wallOffset, NodaTime.Offset savings) <0x2675f30 + 0x00064> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at NodaTime.TimeZones.FixedDateTimeZone..ctor (System.String id, NodaTime.Offset offset, System.String name) <0x2675ce0 + 0x00062> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at NodaTime.TimeZones.FixedDateTimeZone..ctor (System.String id, NodaTime.Offset offset) <0x2675ae0 + 0x00024> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at NodaTime.TimeZones.FixedDateTimeZone..ctor (NodaTime.Offset offset) <0x2675588 + 0x0002c> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at NodaTime.DateTimeZone..cctor () <0x2674d98 + 0x00008> in <56f2b79223fb4321b2f5f4d19722a770>:0 
   --- End of inner exception stack trace ---
  at NodaTime.Instant.InUtc () <0x26744a8 + 0x00046> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at NodaTime.Text.InstantPatternParser+LocalDateTimePatternAdapter.Format (NodaTime.Instant value) <0x2673ed8 + 0x00052> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at NodaTime.Text.Patterns.PatternBclSupport`1[T].Format (T value, System.String patternText, System.IFormatProvider formatProvider) <0x260c658 + 0x00066> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at NodaTime.Instant.ToString () <0x260bac0 + 0x0001a> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeBuilder.AddContent (System.Int32 sequence, System.Object textContent) <0x21632a0 + 0x0002a> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 
  at BlazorDemo.Pages.Counter.BuildRenderTree (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeBuilder builder) <0x21630b8 + 0x000d8> in <1a54eac947034883a4867436f169c3c6>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.ComponentState.RenderIntoBatch (Microsoft.AspNetCore.Blazor.Rendering.RenderBatchBuilder batchBuilder, Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1f13b80 + 0x0006c> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.RenderInExistingBatch (Microsoft.AspNetCore.Blazor.Rendering.RenderQueueEntry renderQueueEntry) <0x1f13728 + 0x00040> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.ProcessRenderQueue () <0x1f0e1a0 + 0x00048> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.AddToRenderQueue (System.Int32 componentId, Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1f0d0e8 + 0x00068> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 
  at Microsoft.AspNetCore.Blazor.Components.RenderHandle.Render (Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1f0cdd0 + 0x00036> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 
  at Microsoft.AspNetCore.Blazor.Routing.Router.Refresh () <0x2034098 + 0x00130> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 
  at Microsoft.AspNetCore.Blazor.Routing.Router.OnLocationChanged (System.Object sender, System.String newAbsoluteUri) <0x215e130 + 0x0002c> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 
  at Microsoft.AspNetCore.Blazor.Browser.Services.BrowserUriHelper.NotifyLocationChanged (System.String newAbsoluteUri) <0x215dfa0 + 0x00026> in <92ed9c6772a34798bccecc99cc26cbcd>:0 
  at NodaTime.Utility.Preconditions.CheckArgument (System.Boolean expression, System.String parameter, System.String message) <0x23f0988 + 0x00020> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at NodaTime.TimeZones.ZoneInterval..ctor (System.String name, NodaTime.Instant start, NodaTime.Instant end, NodaTime.Offset wallOffset, NodaTime.Offset savings) <0x2675f30 + 0x00064> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at NodaTime.TimeZones.FixedDateTimeZone..ctor (System.String id, NodaTime.Offset offset, System.String name) <0x2675ce0 + 0x00062> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at NodaTime.TimeZones.FixedDateTimeZone..ctor (System.String id, NodaTime.Offset offset) <0x2675ae0 + 0x00024> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at NodaTime.TimeZones.FixedDateTimeZone..ctor (NodaTime.Offset offset) <0x2675588 + 0x0002c> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at NodaTime.DateTimeZone..cctor () <0x2674d98 + 0x00008> in <56f2b79223fb4321b2f5f4d19722a770>:0 
   --- End of inner exception stack trace ---
  at NodaTime.Instant.InUtc () <0x26744a8 + 0x00046> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at NodaTime.Text.InstantPatternParser+LocalDateTimePatternAdapter.Format (NodaTime.Instant value) <0x2673ed8 + 0x00052> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at NodaTime.Text.Patterns.PatternBclSupport`1[T].Format (T value, System.String patternText, System.IFormatProvider formatProvider) <0x260c658 + 0x00066> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at NodaTime.Instant.ToString () <0x260bac0 + 0x0001a> in <56f2b79223fb4321b2f5f4d19722a770>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeBuilder.AddContent (System.Int32 sequence, System.Object textContent) <0x21632a0 + 0x0002a> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 
  at BlazorDemo.Pages.Counter.BuildRenderTree (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeBuilder builder) <0x21630b8 + 0x000d8> in <1a54eac947034883a4867436f169c3c6>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.ComponentState.RenderIntoBatch (Microsoft.AspNetCore.Blazor.Rendering.RenderBatchBuilder batchBuilder, Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1f13b80 + 0x0006c> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.RenderInExistingBatch (Microsoft.AspNetCore.Blazor.Rendering.RenderQueueEntry renderQueueEntry) <0x1f13728 + 0x00040> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.ProcessRenderQueue () <0x1f0e1a0 + 0x00048> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.AddToRenderQueue (System.Int32 componentId, Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1f0d0e8 + 0x00068> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 
  at Microsoft.AspNetCore.Blazor.Components.RenderHandle.Render (Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1f0cdd0 + 0x00036> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 
  at Microsoft.AspNetCore.Blazor.Routing.Router.Refresh () <0x2034098 + 0x00130> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 
  at Microsoft.AspNetCore.Blazor.Routing.Router.OnLocationChanged (System.Object sender, System.String newAbsoluteUri) <0x215e130 + 0x0002c> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 
  at Microsoft.AspNetCore.Blazor.Browser.Services.BrowserUriHelper.NotifyLocationChanged (System.String newAbsoluteUri) <0x215dfa0 + 0x00026> in <92ed9c6772a34798bccecc99cc26cbcd>:0 
    at Object.callMethod (http://localhost:51848/_framework/blazor.js:456:23)
    at handleInternalNavigation (http://localhost:51848/_framework/blazor.js:268:28)
    at performInternalNavigation (http://localhost:51848/_framework/blazor.js:262:5)
    at HTMLDocument.<anonymous> (http://localhost:51848/_framework/blazor.js:242:17)
```

Investigating this is going to be "interesting"...

**Comment by jskeet** [comment]
(Using a concrete `LocalDate` *does* work, so I suspect it's constructing `DateTimeZone.Utc` that's the problem.)

**Comment by jskeet** [comment]
The comparison that's failing is basically `Instant.BeforeMinValue < Instant.AfterMaxValue`. Hmm.

**Comment by jskeet** [comment]
It now works - hooray!
