### ISSUE TITLE
Fix using NodaTime 3.0 from net461

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#1153]
This is the cause of #1151, but we can remove BenchmarkDotNet from the picture, as this console app has the same problem:

```csharp
using NodaTime;
using System;

namespace Unstable
{
    class Program
    {
        static void Main(string[] args)
        {
            LocalDateTime start = new LocalDateTime(1976, 6, 19, 8, 40, 0);
            LocalDateTime end = new LocalDateTime(2018, 6, 2, 11, 0, 0);
            Period period = Period.Between(start, end);
            Console.WriteLine(period);
        }
    }
}
```

Exception:

```text
Unhandled Exception: System.Security.VerificationException: Operation could destabilize the runtime.
   at NodaTime.LocalDateTime.get_Calendar()
   at NodaTime.Period.Between(LocalDateTime start, LocalDateTime end, PeriodUnits units)
   at NodaTime.Period.Between(LocalDateTime start, LocalDateTime end)
   at Unstable.Program.Main(String[] args)
```

Will investigate why.

**Comment by jskeet** [comment]
(Fixed by #1154.)
