### ISSUE TITLE
Parsing issue on 2018f  file

### ISSUE THREAD

**Issue by feancosa** [nodatime/nodatime#1211]
I am not sure if this is an issue with the library or with IANA database, but I am getting the following exception after the 2018f file has been released (I am using 2.3.0 nodatime but I have checked with 2.4.1 and it also happens):

System.FormatException: Invalid time in rules: 25:00
   at NodaTime.TzdbCompiler.Tzdb.ParserHelper.ParseTime(String text) in d:\build\INIW-MAS76-JOB1\Indji.IndjiWatch\IndjiWatch2\lib\NodaTime\NodaTime.TzdbCompiler\Tzdb\ParserHelper.cs:line 157
   at NodaTime.TzdbCompiler.Tzdb.TzdbZoneInfoParser.ParseDateTimeOfYear(Tokens tokens, Boolean forRule) in d:\build\INIW-MAS76-JOB1\Indji.IndjiWatch\IndjiWatch2\lib\NodaTime\NodaTime.TzdbCompiler\Tzdb\TzdbZoneInfoParser.cs:line 208
   at NodaTime.TzdbCompiler.Tzdb.TzdbZoneInfoParser.ParseRule(Tokens tokens) in d:\build\INIW-MAS76-JOB1\Indji.IndjiWatch\IndjiWatch2\lib\NodaTime\NodaTime.TzdbCompiler\Tzdb\TzdbZoneInfoParser.cs:line 356
   at NodaTime.TzdbCompiler.Tzdb.TzdbZoneInfoParser.ParseLine(String line, String previousZone, TzdbDatabase database) in d:\build\INIW-MAS76-JOB1\Indji.IndjiWatch\IndjiWatch2\lib\NodaTime\NodaTime.TzdbCompiler\Tzdb\TzdbZoneInfoParser.cs:line 286
   at NodaTime.TzdbCompiler.Tzdb.TzdbZoneInfoParser.Parse(TextReader reader, TzdbDatabase database) in d:\build\INIW-MAS76-JOB1\Indji.IndjiWatch\IndjiWatch2\lib\NodaTime\NodaTime.TzdbCompiler\Tzdb\TzdbZoneInfoParser.cs:line 128
   at NodaTime.TzdbCompiler.Tzdb.TzdbZoneInfoCompiler.LoadZoneFiles(FileSource source, TzdbDatabase database) in d:\build\INIW-MAS76-JOB1\Indji.IndjiWatch\IndjiWatch2\lib\NodaTime\NodaTime.TzdbCompiler\Tzdb\TzdbZoneInfoCompiler.cs:line 79
   at NodaTime.TzdbCompiler.Tzdb.TzdbZoneInfoCompiler.Compile(String path) in d:\build\INIW-MAS76-JOB1\Indji.IndjiWatch\IndjiWatch2\lib\NodaTime\NodaTime.TzdbCompiler\Tzdb\TzdbZoneInfoCompiler.cs:line 65
   at Indji.Watch.ApplicationServices.Tools.Controllers.TimeZonesController.CompileIanaDb(FileData ianaFileData) in d:\build\INIW-MAS76-JOB1\Indji.IndjiWatch\IndjiWatch2\Indji.Watch.ApplicationServices.Tools\Controllers\TimeZonesController.cs:line 47
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by jskeet** [comment]
TzdbCompiler isn't part of any released NuGet package, so it looks like you must have cloned the source code for that project. It was TzdbCompiler that needed changing to fix the issue, so if you clone the repository *now*, it should be okay.

I'm intrigued to know why you're trying to parse the data yourself anyway, to be honest. Any reason not to use the nzd files we provide?

**Comment by feancosa** [comment]
Thanks for the quick response.

The reason at the time was that we did not want to introduce an additional potential delay on getting the latest version of the time zones (once IANA release the new db we would have to wait for the tzdb to be available), and as the compiler was available then it made sense to just use it.

Having said that we now realize that time zones don't really change that often (at least the ones that we mainly use), and it looks like you are pretty quick on providing a tzdb file. This would definitely make us rethink if to actually recompile the fix you mention or just directly get your tzdb.

thanks again!

**Comment by jskeet** [comment]
Yes, I almost always manage to provide a new nzd file within 24 hours. The URL is always available at https://nodatime.org/tzdb/latest.txt, so that can be automated from client apps.

One reason it's worth waiting for an nzd file is that I validate that it has the same transition points as zic produces, via tzvalidate (https://github.com/nodatime/tzvalidate).

I'll close this issue now, as I don't think there's any further action to take in this repo.
