### ISSUE TITLE
API docs generation broken (again)

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#1268]
Need to investigate why - fails on both bagpuss and locally.

Could well be due to update to 3.0 preview 2.

```text
Modifying YAML files for unstable

Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DocfxAnnotationGenerator.Program.FindDocument(Release release, Dictionary`2 files, String uid) in C:\Users\skeet\Test\Projects\nodatime\build\DocfxAnnotationGenerator\Program.cs:line 252
   at DocfxAnnotationGenerator.Program.AnnotateNotNullParameters(Release release, Dictionary`2 files) in C:\Users\skeet\Test\Projects\nodatime\build\DocfxAnnotationGenerator\Program.cs:line 157
   at DocfxAnnotationGenerator.Program.ModifyYamlFiles() in C:\Users\skeet\Test\Projects\nodatime\build\DocfxAnnotationGenerator\Program.cs:line 135
   at DocfxAnnotationGenerator.Program.Main(String[] args) in C:\Users\skeet\Test\Projects\nodatime\build\DocfxAnnotationGenerator\Program.cs:line 39
```

**Comment by jskeet** [comment]
The fact that it's in the AnnotateNotNullParameters reminds me that I'll need to work out what to do when we remove the `[NotNull]` attributes, too...

**Comment by jskeet** [comment]
Some warnings generating the docfx metadata may be relevant:

```text
[19-01-31 09:59:02.629]Warning:[ExtractMetadata]Invalid cref value "!:Iso" found in triple-slash-comments for CalendarSystem defined in unstable/src/NodaTime/CalendarSystem.cs Line 40, ignored.
[19-01-31 09:59:02.639]Warning:[ExtractMetadata]Invalid cref value "!:GetHebrewCalendar(HebrewMonthNumbering)" found in triple-slash-comments for CalendarSystem defined in unstable/src/NodaTime/CalendarSystem.cs Line 40, ignored.
[19-01-31 09:59:02.644]Warning:[ExtractMetadata]Invalid cref value "!:Id" found in triple-slash-comments for ForId defined in unstable/src/NodaTime/CalendarSystem.cs Line 105, ignored.
[19-01-31 09:59:04.703]Warning:[ExtractMetadata]Invalid cref value "!:CalendarSystem.GetHebrewCalendar" found in triple-slash-comments for HebrewMonthNumbering defined in unstable/src/NodaTime/Calendars/HebrewMonthNumbering.cs Line 15, ignored.
[19-01-31 09:59:04.754]Warning:[ExtractMetadata]Invalid cref value "!:CalendarSystem.GetIslamicCalendar" found in triple-slash-comments for IslamicEpoch defined in unstable/src/NodaTime/Calendars/IslamicEpoch.cs Line 16, ignored.
[19-01-31 09:59:04.762]Warning:[ExtractMetadata]Invalid cref value "!:CalendarSystem.GetIslamicCalendar" found in triple-slash-comments for IslamicLeapYearPattern defined in unstable/src/NodaTime/Calendars/IslamicLeapYearPattern.cs Line 25, ignored.
```

**Comment by jskeet** [comment]
Okay, fixed for now, barring #1269. We have guards in place to break if we don't get all the members we expect.

**Comment by Name210** [comment]
> Es necesario investigar por qué: falla tanto en bagpuss como localmente.
> 
> Bien podría deberse a la actualización a la versión preliminar 3.0 2.
> 
> ```
> Modifying YAML files for unstable
> 
> Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
>    at System.ThrowHelper.ThrowKeyNotFoundException()
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at DocfxAnnotationGenerator.Program.FindDocument(Release release, Dictionary`2 files, String uid) in C:\Users\skeet\Test\Projects\nodatime\build\DocfxAnnotationGenerator\Program.cs:line 252
>    at DocfxAnnotationGenerator.Program.AnnotateNotNullParameters(Release release, Dictionary`2 files) in C:\Users\skeet\Test\Projects\nodatime\build\DocfxAnnotationGenerator\Program.cs:line 157
>    at DocfxAnnotationGenerator.Program.ModifyYamlFiles() in C:\Users\skeet\Test\Projects\nodatime\build\DocfxAnnotationGenerator\Program.cs:line 135
>    at DocfxAnnotationGenerator.Program.Main(String[] args) in C:\Users\skeet\Test\Projects\nodatime\build\DocfxAnnotationGenerator\Program.cs:line 39
> ```

**Comment by jskeet** [comment]
(Spammer blocked.)
