### ISSUE TITLE
Support F# Option type in NodaTime.Serialization.JsonNet (Discriminated Union)

### ISSUE THREAD

**Issue by buvinghausen** [nodatime/nodatime#595]
I was working on fixing the Swashbuckle.NodaTime package to support both Nullable & Option types and I ran across the problem of NodaTime.Serialization.JsonNet not working when a DiscriminatedUnion type is used.

I will look through the source in both Json.NET and NodaTime.Serialization.JsonNet and see if I can't get a working solution to PR but in the meantime here's the stack trace I just wanted to get this into the backlog since I'm planning on cutting one of my APIs over to F# in the not too distant future and would like to use both NodaTime and Swashbuckle.

Newtonsoft.Json.JsonSerializationException : Unexpected end when reading JSON. Path '', line 1, position 22.
   at Newtonsoft.Json.JsonReader.ReadAndAssert()
   at Newtonsoft.Json.Converters.DiscriminatedUnionConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Swashbuckle.NodaTime.Tests.SchemasTests.deserialize[T](String json) in SchemasTests.fs:line 17
   at Swashbuckle.NodaTime.Tests.SchemasTests.tryDeserializeExample[T](Schema schema) in SchemasTests.fs:line 20
   at Swashbuckle.NodaTime.Tests.SchemasTests.Examples in schemas should be deserializable() in SchemasTests.fs:line 55

**Comment by jskeet** [comment]
Do discriminated unions work for other types? I doubt that this is specific to Noda Time, although it may be specific to custom serializers.

**Comment by jskeet** [comment]
Ping?

**Comment by jskeet** [comment]
Closing for now - please reopen if you have more information, particularly if Noda Time fails where similar things work.
