### ISSUE TITLE
nodatime.org is down

### ISSUE THREAD

**Issue by jnyrup** [nodatime/nodatime#751]
:(  Oops.
500 Internal Server Error
System.Net.Http.WinHttpException
The operation timed out
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) 
at System.Net.Http.<StartRequest>d__105.MoveNext()
System.Net.Http.HttpRequestException
An error occurred while sending the request.
at Google.Apis.Requests.ClientServiceRequest.Execute() 
at Google.Api.Gax.Rest.<AsRawResponses>d__3.MoveNext() 
at System.Linq.<SelectManyIterator>d__159.MoveNext() 
at System.Linq.WhereSelectEnumerableIterator.MoveNext() 
at System.Collections.Generic.EnumerableHelpers.ToArray<T>(IEnumerable<T> source, Int32& length) 
at System.Linq.Buffer..ctor(IEnumerable<TElement> source) 
at System.Linq.OrderedEnumerable.ToList() 
at System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source) 
at NodaTime.Web.Models.GoogleStorageReleaseRepository.MaybeUpdateReleases() in c:\Users\skeet\Test\Projects\nodatime\src\NodaTime.Web\Models\GoogleStorageReleaseRepository.cs:line 65 
at NodaTime.Web.Models.GoogleStorageReleaseRepository.GetReleases() in c:\Users\skeet\Test\Projects\nodatime\src\NodaTime.Web\Models\GoogleStorageReleaseRepository.cs:line 40 
at NodaTime.Web.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in c:\Users\skeet\Test\Projects\nodatime\src\NodaTime.Web\Startup.cs:line 94
System.Reflection.TargetInvocationException
Exception has been thrown by the target of an invocation.
at System.RuntimeMethodHandle.InvokeMethod(object target, Object[] arguments, Signature sig, bool constructor) 
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(object obj, Object[] parameters, Object[] arguments) 
at System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) 
at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder) 
at Microsoft.AspNetCore.Hosting.Internal.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder) 
at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app) 
at Microsoft.AspNetCore.Server.IISIntegration.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app) 
at Microsoft.AspNetCore.Hosting.Internal.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder) 
at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Show raw exception details
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Net.Http.WinHttpHandler.d__105.MoveNext()
   --- End of inner exception stack trace ---
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at Google.Api.Gax.Rest.RestPagedEnumerable`3.d__3.MoveNext()
   at System.Linq.Enumerable.d__159`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NodaTime.Web.Models.GoogleStorageReleaseRepository.MaybeUpdateReleases() in c:\Users\skeet\Test\Projects\nodatime\src\NodaTime.Web\Models\GoogleStorageReleaseRepository.cs:line 65
   at NodaTime.Web.Models.GoogleStorageReleaseRepository.GetReleases() in c:\Users\skeet\Test\Projects\nodatime\src\NodaTime.Web\Models\GoogleStorageReleaseRepository.cs:line 40
   at NodaTime.Web.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in c:\Users\skeet\Test\Projects\nodatime\src\NodaTime.Web\Startup.cs:line 94
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.<>c__DisplayClass4_0.b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass2_0.b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
.NET Core X86 v4.1.0.0   |   Microsoft.AspNetCore.Hosting version 1.0.2   |   Microsoft Windows 6.2.9200    |   Need help?

**Comment by jskeet** [comment]
Yes, I'm working on it now.

**Comment by jskeet** [comment]
Partially fixed - but the TZDB downloads are still broken.

**Comment by malcolmr** [comment]
@jskeet Everything is fixed now except that the GCS list operation is stubbed out (per cfb01648)?

**Comment by jskeet** [comment]
Well, everything to do with GCS is removed - listing objects for TZDB and NodaTime releases, and fetching TZDB releases from storage to serve them.

I'm trying to work out why we can't fetch http://storage.googleapis.com from Azure. (At least, from some of Azure. I've got *one* web application that works, two that fail, and two Linux VMs that fail.)

**Comment by jskeet** [comment]
Back up now, and it's easier to remove the GCS dependency in a rush for the future, but let's hope it doesn't come to that. (If we move to container engine, it'll make it even less likely...)
