### ISSUE TITLE
Investigate docs build issue

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#989]
The Bagpuss automated documentation build appears to be failing. I should work out why. Probably worth fixing #938 at the same time.

**Comment by jskeet** [comment]
Here's the exception we're getting:

```text
Unhandled Exception: System.IO.IOException: The directory name is invalid
   at System.IO.Win32FileSystemEnumerableIterator`1.HandleError(Int32 errorCode, String path)
   at System.IO.Win32FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.Win32FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler)
   at System.IO.Win32FileSystemEnumerableFactory.CreateFileNameIterator(String path, String originalUserPath, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.Win32FileSystem.EnumeratePaths(String fullPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)
   at System.IO.Directory.EnumerateFileSystemNames(String path, String searchPattern, SearchOption searchOption, Boolean includeFiles, Boolean includeDirs)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at DocfxYamlLoader.Release.Load(String directory, String version) in C:\Users\Jon\NodaTime-Web-Builds\648a57431746545709cee23441c0162ea59227e7\nodatime\build\DocfxYamlLoader\Release.cs:line 36
   at ReleaseDiffGenerator.Program.Main(String[] args) in C:\Users\Jon\NodaTime-Web-Builds\648a57431746545709cee23441c0162ea59227e7\nodatime\build\ReleaseDiffGenerator\Program.cs:line 21
```

**Comment by jskeet** [comment]
Ah - it's the *last* call to `ReleaseDiffGenerator`, and the problem is with `tmp/docfx/unstable` which is a *file* when I run it on bagpass, but a *directory* when I run locally. Weird - and possibly related to different docfx versions.

**Comment by jskeet** [comment]
Ah - it's because `docfx` fails, but only with warnings:

```text
[17-10-15 06:01:04.603]Warning:[ExtractMetadata]Workspace failed with: [Failure] Msbuild failed when processing the file 'C:\Users\Jon\NodaTime-Web-Builds\648a57431746545709cee23441c0162ea59227e7\nodatime\build\tmp\docfx\unstable\src\NodaTime\NodaTime.csproj' with message: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\MSBuild\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\Jon\NodaTime-Web-Builds\648a57431746545709cee23441c0162ea59227e7\nodatime\build\tmp\docfx\unstable\src\NodaTime\NodaTime.csproj
[17-10-15 06:01:04.603]Warning:[ExtractMetadata]Workspace failed with: [Failure] Msbuild failed when processing the file 'C:\Users\Jon\NodaTime-Web-Builds\648a57431746545709cee23441c0162ea59227e7\nodatime\build\tmp\docfx\unstable\src\NodaTime.Serialization.JsonNet\NodaTime.Serialization.JsonNet.csproj' with message: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\MSBuild\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\Jon\NodaTime-Web-Builds\648a57431746545709cee23441c0162ea59227e7\nodatime\build\tmp\docfx\unstable\src\NodaTime.Serialization.JsonNet\NodaTime.Serialization.JsonNet.csproj
[17-10-15 06:01:04.603]Warning:[ExtractMetadata]Workspace failed with: [Failure] Msbuild failed when processing the file 'C:\Users\Jon\NodaTime-Web-Builds\648a57431746545709cee23441c0162ea59227e7\nodatime\build\tmp\docfx\unstable\src\NodaTime.Testing\NodaTime.Testing.csproj' with message: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\MSBuild\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\Jon\NodaTime-Web-Builds\648a57431746545709cee23441c0162ea59227e7\nodatime\build\tmp\docfx\unstable\src\NodaTime.Testing\NodaTime.Testing.csproj
[17-10-15 06:01:04.603]Warning:[ExtractMetadata]Project 'C:\Users\Jon\NodaTime-Web-Builds\648a57431746545709cee23441c0162ea59227e7\nodatime\build\tmp\docfx\unstable\src\NodaTime.Serialization.JsonNet\NodaTime.Serialization.JsonNet.csproj' does not contain any documents.
[17-10-15 06:01:04.603]Warning:[ExtractMetadata]Project 'C:\Users\Jon\NodaTime-Web-Builds\648a57431746545709cee23441c0162ea59227e7\nodatime\build\tmp\docfx\unstable\src\NodaTime\NodaTime.csproj' does not contain any documents.
[17-10-15 06:01:04.603]Warning:[ExtractMetadata]Project 'C:\Users\Jon\NodaTime-Web-Builds\648a57431746545709cee23441c0162ea59227e7\nodatime\build\tmp\docfx\unstable\src\NodaTime.Testing\NodaTime.Testing.csproj' does not contain any documents.
[17-10-15 06:01:04.603]Warning:[ExtractMetadata]No metadata is generated for NodaTime.Serialization.JsonNet,NodaTime,NodaTime.Testing.
	7 Warning(s)
```

Will validate that this is due to docfx versions, and then we can fix #938 which would fix this.

**Comment by jskeet** [comment]
Curiouser and curiouser - on Bagpuss it works when run interactively, but not when run from the scheduled task. Very odd.

**Comment by jskeet** [comment]
It looks like this was a problem when I was first starting the automation (August 9th) but then it went away until the commit on October 5th. (It worked on September 29th.)

I wonder whether there was a Windows update on Bagpuss or similar that changed things. Still looking into it...

**Comment by jskeet** [comment]
Aha - more interesting bit of failure log:

> The imported project "C:\Program Files (x86)\Microsoft
Visual Studio\VS15Preview\MSBuild\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props" was not found

I suspect I installed the full release of VS2017 only a couple of weeks ago, hence the change in behaviour. Now to work out what the difference is in terms of environment...

**Comment by jskeet** [comment]
Okay, it looks like this is the docfx+.NET Core 2.0 issue I've seen before, but this time via a non-development command prompt issue. Adding an environment variable for VSINSTALLDIR on Bagpuss has sorted it, I think. (We'll see when it tries the next build.) Still need to do 938 though.
